print more on exercise check failure

diff --git a/Makefile.coq.local b/Makefile.coq.local
--- a/Makefile.coq.local
+++ b/Makefile.coq.local
@@ -12,4 +12,4 @@ $(EXERCISES): exercises/%.v: solutions/%.v gen-exercises.awk
 # CI make target
 ci: all
 	+@make -B exercises # force make (in case exercise files have been edited directly)
-	if [ -n "$$(git status --porcelain)" ]; then echo 'ERROR: Exercise files are not up-to-date with solutions.'; exit 1; fi
+	if [ -n "$$(git status --porcelain)" ]; then echo 'ERROR: Exercise files are not up-to-date with solutions. `git status` after re-making them:'; git status; exit 1; fi
